config {
  type: "table",
  schema: "analytics",
  tags: ["zendesk"],
  description: "Monthly counts of tickets created",
  columns: {
    created_date: "Ticket creation month",
    count: "The number of tickets created"
  },
  dependencies: [
    "freshness_zendesk_tickets",
    "intermediate_int_zendesk_ticket_assertions_uniqueKey_0"
  ]
}

SELECT
  DATE_TRUNC(DATE(created_at), MONTH) AS created_month,
  COUNT(DISTINCT id) as count
FROM ${ref("int_zendesk_ticket")}
GROUP BY 1