config {
  type: "table",
  schema: "analytics",
  tags: ["zendesk"],
  description: "Daily counts of tickets created",
  columns: {
    created_date: "Ticket creation date",
    count: "The number of tickets created"
  },
  dependencies: [
    "freshness_zendesk_tickets",
    "sources_src_zendesk_ticket_assertions_uniqueKey_0"
  ]
}

SELECT
  DATE(created_at) AS created_date,
  COUNT(DISTINCT id) as count
FROM ${ref("src_zendesk_ticket")}
GROUP BY 1